/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mingspy_mseg_MsegJNI */

#ifndef _Included_com_mingspy_mseg_MsegJNI
#define _Included_com_mingspy_mseg_MsegJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mingspy_mseg_MsegJNI
 * Method:    ConfigInit
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_mingspy_mseg_MsegJNI_ConfigInit
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_mingspy_mseg_MsegJNI
 * Method:    ConfigSet
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_mingspy_mseg_MsegJNI_ConfigSet
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_mingspy_mseg_MsegJNI
 * Method:    MsegInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mingspy_mseg_MsegJNI_MsegInit
  (JNIEnv *, jclass);

/*
 * Class:     com_mingspy_mseg_MsegJNI
 * Method:    ForwardSplit
 * Signature: (Ljava/lang/String;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_mingspy_mseg_MsegJNI_ForwardSplit
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_mingspy_mseg_MsegJNI
 * Method:    FullSplit
 * Signature: (Ljava/lang/String;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_mingspy_mseg_MsegJNI_FullSplit
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_mingspy_mseg_MsegJNI
 * Method:    SmartSplit
 * Signature: (Ljava/lang/String;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_mingspy_mseg_MsegJNI_SmartSplit
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_mingspy_mseg_MsegJNI
 * Method:    BackwardSplit
 * Signature: (Ljava/lang/String;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_mingspy_mseg_MsegJNI_BackwardSplit
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_mingspy_mseg_MsegJNI
 * Method:    Tagging
 * Signature: (Ljava/lang/String;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL Java_com_mingspy_mseg_MsegJNI_Tagging
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
