/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mingspy_jseg_JSegJNI */

#ifndef _Included_com_mingspy_jseg_JSegJNI
#define _Included_com_mingspy_jseg_JSegJNI
#ifdef __cplusplus
extern "C" {
#endif

#if 0
// test not use cpp header file.
/*
 * Class:     com_mingspy_jseg_JSegJNI
 * Method:    MaxSplit
 * Signature: (Ljava/lang/String;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL JNI_MaxSplit
(JNIEnv *, jclass, jstring);

/*
 * Class:     com_mingspy_jseg_JSegJNI
 * Method:    FullSplit
 * Signature: (Ljava/lang/String;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL JNI_FullSplit
(JNIEnv *, jclass, jstring);

/*
 * Class:     com_mingspy_jseg_JSegJNI
 * Method:    UniGramSplit
 * Signature: (Ljava/lang/String;)Ljava/util/List;
 */
JNIEXPORT jobject JNICALL JNI_UniGramSplit
(JNIEnv *, jclass, jstring);

#endif

#ifdef __cplusplus
}
#endif
#endif
